---
title: ""
output:
  html_document:
    df_print: kable
    toc: true
    toc_float : yes
    toc_depth : 4
---

<br>

# Computational Biology Tools 

### AMARETTO-Hub

<p style="text-align: justify">
AMARETTO-Hub is a Knowledge Graph-based software platform that leverages neo4j and shiny to embed and interactively interrogate results generated by the *AMARETTO software toolbox which offers modular and complementary solutions to multimodal and multiscale network-based fusion of multi-omics, clinical, imaging, and perturbation data across studies of patients, etiologies and model systems of cancer.
</p>

**People**: [Nathalie Pochet](https://scholar.google.com/citations?user=Xz0qKWgAAAAJ&hl=en)

**GitHub**:
[https://github.com/broadinstitute/AMARETTO-Hub](https://github.com/broadinstitute/AMARETTO-Hub)

<br>

### Dprofiler (Under Development)

<p style="text-align: justify">
Dprofiler computationally profiles a set of targeted samples by connecting them to reference expression datasets with phenotypic profiles of interest. Building on these reference profiles of phenotypic groups, Dprofiler evaluates bulk RNA samples, detect possibly existing anomalies and heterogeneities, and further explores causes and sources of distinct molecular patterns with the aid of single cell maps and other reference gene expression datasets.
</p>

**People**: [Alper Kucukural](https://profiles.umassmed.edu/display/11976488) and [Manuel Garber](https://www.umassmed.edu/garberlab/)

**GitHub**:
[https://github.com/UMMS-Biocore/dprofiler](https://github.com/UMMS-Biocore/dprofiler)

<br>

### CodonUtil (Under Development)

<p style="text-align: justify">
CodonUtil is an R package that allows processing, analysis and visualization of (single or paired) codon usage of RNA sequences. It allows building genome tracks on the usage of codons on genomes of interest and provides normalization on quantified counts of datasets with specific codon features. 
</p>

**People**: [Markus Landthaler](https://www.mdc-berlin.de/landthaler)

**GitHub**:
[https://github.com/LandthalerLab/CodonUtil](https://github.com/LandthalerLab/CodonUtil)

<br>

# Statistical Software 

### PCDSL

<p style="text-align: justify">
The Proximity Catch Digraphs for Statistical Learning and Classification. Proximity Catch Digraphs (PCDs) are special types of proximity graphs.
</p>

**People**: [Elvan Ceyhan](http://webhome.auburn.edu/~ezc0066/)

**GitHub**:
[https://github.com/Artur-man/PCDSL](https://github.com/Artur-man/PCDSL)

<br>

### DandEFA

<p style="text-align: justify">
DandEFA contains the function used to create the Dandelion Plot. Dandelion Plot is a visualization method for R-mode Exploratory Factor Analysis.
</p>

**People**: [Erhan Cene](https://scholar.google.com/citations?hl=de&user=o7F1mWAAAAAJ&view_op=list_works&sortby=pubdate), [Ahmet Sedef](https://www.linkedin.com/in/ahmet-sedef-6129291a/), [Ibrahim Demir](https://www.linkedin.com/in/ahmet-sedef-6129291a/)

**CRAN**:
[https://cran.r-project.org/web/packages/DandEFA](https://cran.r-project.org/web/packages/DandEFA/index.html)

<br>
